### ISSUE TITLE
RFC: Documentation refactor

### ISSUE THREAD

**Issue by bbros-dev** [tag1consulting/goose#306]
We've struggled coming to grips with Goose.
Partly because we're unfamiliar with it's code base.
Partly because we're unfamiliar with the (Locust) model it uses.
Partly because documentation is scattered across different blogs posts that refer to different Goose versions.
Partly because the documentation is structured as single file.

Looking at the possible documentation it seems the time may have come to restructure the documentation?
If this is agreed we'd be happy to contribute, but we don't want to sink time into anything that is then declined and we have to maintain as a fork.

Proposals (scope):

- [x] Restructure (not rewrite) the documentation.  Includes gathering blog content. Proposal: markdown
- [x] Documentation generated as static site. Proposal: mdbook
- [x] #314. Proposal: GitHub pages (migrate to https://goose.rs once that is setup)
- [x] #316. Proposal: `book/src`
- [x] #315. Proposal: [actions-mdbook](https://github.com/peaceiris/actions-mdbook)
- [x] #317.

**Comment by jeremyandrews** [comment]
My intent/goal is to turn the README and other documentation blogs into an online book, as are common for many Rust projects. In the mid-term I'm aiming for two books, one with that's the definitive reference, and one with useful recipes/snippets, structured as a cookbook. The books will still be built from the code (necessary to keep it in sync with the code), but likely will be hosted at an upcoming https://goose.rs/ website.

**Comment by bbros-dev** [comment]
Okay. Is there tooling you had in mind? Or a reference site you'd like to emulate that we can replicate?

**Comment by jeremyandrews** [comment]
I believe the Rust book is using mdBook:
 - https://rust-lang.github.io/mdBook/
 - https://docs.rs/mdbook/0.4.10/mdbook/index.html
 - https://github.com/rust-lang/mdBook

**Comment by bbros-dev** [comment]
Does that proposed setup look acceptable?

**Comment by jeremyandrews** [comment]
Yes. This is the direction I was planning to go when I had time for this. If you can review how a major Rust project (ie the language itself) is integrating this with their project, that would be ideal. I can try and make time to explore this next week as well, if that helps.

**Comment by bbros-dev** [comment]
> If you can review how a major Rust project (ie the language itself) is integrating this with their project, that would be ideal.

Yup, we've looked there and what we've outlined seems to be what rustaceans do/use

> I can try and make time to explore this next week as well, if that helps.

We'll have a crack and see how we go.  We'll keep this issue open of issues that arise, e.g. book outline/skeleton.
